name: Deno

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up repo
        uses: actions/checkout@v2

      - name: Set up Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Cache Dependencies
        run: deno cache dev_deps.ts

      - name: Run Tests
        run: deno test -A --unstable
