name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up repo
        uses: actions/checkout@v2

      - name: Set up Deno
        uses: denolib/setup-deno@v2

      - name: Create package
        run: deno run -A scripts/build_npm.ts ${{ github.event.release.tag_name }}

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: "./npm/package.json"
